# Generated by Django 5.0.6 on 2024-08-29 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wearhouse', '0002_stockunit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockunit',
            options={'get_latest_by': '-modified', 'verbose_name_plural': 'Stock units'},
        ),
        migrations.AddField(
            model_name='stockunit',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Stock unit name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wearhouse',
            name='stockunits',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wearhouse.stockunit', verbose_name='Stock units'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='stockunit',
            table='stockunits',
        ),
    ]
