# Generated by Django 5.0.6 on 2024-08-29 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wearhouse', '0005_stockunit_cacca_alter_stockunit_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockunit',
            name='cacca',
        ),
        migrations.AlterField(
            model_name='stockunit',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Stock unit name'),
        ),
    ]
