# Generated by Django 5.0.6 on 2024-08-29 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wearhouse', '0006_remove_stockunit_cacca_alter_stockunit_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockunit',
            name='name',
            field=models.CharField(max_length=51, unique=True, verbose_name='Stock unit name'),
        ),
    ]
