# Generated by Django 5.0.6 on 2024-08-30 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wearhouse', '0007_alter_stockunit_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wearhouse',
            name='stockunits',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wearhouse.stockunit', verbose_name='Stock units'),
        ),
    ]
