# Generated by Django 5.0.6 on 2024-07-07 22:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='activate_date',
        ),
        migrations.RemoveField(
            model_name='item',
            name='deactivate_date',
        ),
        migrations.RemoveField(
            model_name='item',
            name='status',
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
