# Generated by Django 5.0.6 on 2024-07-10 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_remove_item_activate_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'get_latest_by': '-modified', 'ordering': ['name'], 'verbose_name_plural': 'Items'},
        ),
        migrations.AlterModelTableComment(
            name='item',
            table_comment='Items basic informations',
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterModelTable(
            name='item',
            table='items',
        ),
    ]
