# Generated by Django 5.0.6 on 2024-07-15 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_alter_item_options_alter_item_table_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='components',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='items.item'),
        ),
    ]
