# Generated by Django 5.0.6 on 2024-07-15 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_item_created_by_item_last_modified_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='components',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.item'),
        ),
    ]
