# Generated by Django 5.0.6 on 2024-07-20 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_alter_item_components'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='depth_mm',
            field=models.FloatField(default=0.0, verbose_name='Depth in millimeters'),
        ),
        migrations.AddField(
            model_name='item',
            name='height_mm',
            field=models.FloatField(default=0.0, verbose_name='Heigth in millimeters'),
        ),
        migrations.AddField(
            model_name='item',
            name='width_mm',
            field=models.FloatField(default=0.0, verbose_name='Width in millimeters'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
