# Generated by Django 5.0.6 on 2024-07-21 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_alter_item_last_modified_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='weigth_g',
            field=models.FloatField(default=0.0, verbose_name='Weigth in grams'),
        ),
    ]
