# Generated by Django 5.0.6 on 2024-07-22 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_item_weigth_g'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='depth_mm',
        ),
        migrations.RemoveField(
            model_name='item',
            name='height_mm',
        ),
        migrations.RemoveField(
            model_name='item',
            name='width_mm',
        ),
        migrations.AddField(
            model_name='item',
            name='volume_cm3',
            field=models.FloatField(default=0.0, verbose_name='Volume in cm3'),
        ),
    ]
